In [33]:
# This is how you import the library
# Numpy = NUMERICAL PYTHON

import numpy as np
import time

In [35]:
# summation first 1Million numbers
start_time = time.time()
values = np.arange(100000000, dtype=np.uint64)
print(values)
result = np.sum(values)
end = time.time()
elapsed_time = end - start_time
print("The time of execution for the numpy version is :",
      (elapsed_time) * 10**3, "ms")
print(result)
print("====================================")

[       0        1        2 ... 99999997 99999998 99999999]
The time of execution for the numpy version is : 383.1615447998047 ms
4999999950000000


In [39]:
start_time = time.time()
summation = 0
x = range(0, 100000000)
for n in x:
    summation = summation + n
end = time.time()
elapsed_time = end - start_time
print("The time of execution for the python version is :",
      (elapsed_time) * 10**3, "ms")
print(summation)

The time of execution for the python version is : 13359.179019927979 ms
4999999950000000


In [41]:
start_time = time.time()
summation = 0
summation = sum(list(range(0, 100000000)))
end = time.time()
elapsed_time = end - start_time
print("The time of execution for the python version is :",
      (elapsed_time) * 10**3, "ms")
print(summation)

The time of execution for the python version is : 23888.935327529907 ms
4999999950000000


In [11]:
# This is just a typical and simple python list. This is has nothing to do
# with numpy
mylist = [1,2,3]

In [13]:
# here we are type-casting a python-list into a numpy-array
np.array(mylist)

array([1, 2, 3])

In [15]:
# this is a nested-python-list, nothing to do with numpy 
nested_list = [[1,2], [3,4], [5,6]]

In [17]:
print(nested_list)

[[1, 2], [3, 4], [5, 6]]


In [19]:
# here we are type-casting a nested-python-list into a numpy-array
# in this case the array will be a 2-D array(matrix)
print(np.array(nested_list))

[[1 2]
 [3 4]
 [5 6]]


In [21]:
# arange will allow you to define a set of values as follows
# arange(start, stop, step)
# BE AWARE THAT THE STOP VALUE IS NOT INCLUDED
# example 1
print(np.arange(0,10,2))

[0 2 4 6 8]


In [23]:
# arange will allow you to define a set of values as follows
# arange(start, stop, step)
# BE AWARE THAT THE STOP VALUE IS NOT INCLUDED
# example 2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [25]:
# zeros.
#very useful to quickly create arrays or matrices full of zeroes
np.zeros(3)

array([0., 0., 0.])

In [27]:
# why is failing ???? you will see why on the cell below
np.zeros(4,10)

TypeError: Cannot interpret '10' as a data type

In [29]:
# this one works? why? what is the diference? 
# answer: it expects a tuple
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
# ones.
#very useful to quickly create arrays or matrices full of ones
np.ones(3)

array([1., 1., 1.])

In [ ]:
# why it fails????
np.ones(4,10)

In [33]:
# this one works? why? what is the diference? 
# answer: it expects a tuple
np.ones((4,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [35]:
# Linspace - Linearly spaced - example 1
# Evenly distributed numbers over an interval of interest
# Format: linspace(start, stop, how many #s  you want)
# linspace(0,10,3)  MEANS
# a. start = 1st value will be zero
# b. stop = last value will be 10
# c. # of samples = 3
# BE AWARE THAT THIS INSTRUCTIONS INCLUDES-INCLUDES-INCLUDES the stop value
# VERY - VERY SIMILAR TO MATLAB AND OCTAVE
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [37]:
# Linspace - Linearly spaced - example 2
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [39]:
# Linspace - Linearly spaced - example 3
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [41]:
# Identity matrix  = diagonal is equal to 1, everything else is zero
# Identity matrices are always square.
# for such reason you only need one number
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
# generatates an array with two random numbers
# Create an array of the given shape and populate it with random samples 
# from a uniform distribution over [0, 1).
#https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html 

np.random.rand(2)

array([0.87402238, 0.13598794])

In [45]:
# generatates an array with two random numbers
# random samples from a uniform distribution
# a Tuple is not required here
# Again, values between [0,1)

np.random.rand(3,4)  #here we are asking for a 3x4 matrix full of random numbers

array([[0.83183179, 0.38794942, 0.18202183, 0.09690545],
       [0.6452022 , 0.59490129, 0.70273755, 0.43726196],
       [0.457976  , 0.13137185, 0.8121324 , 0.61833759]])

In [47]:
# generatates an array with two random numbers
# random samples from a "standard normal" distribution
# mean 0 and variance 1
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html

np.random.randn(5,5)

array([[-0.76369467, -1.0653628 ,  1.19520787,  0.55427914, -0.32073154],
       [-0.78936716, -3.11500396,  1.80738829, -0.64532174,  0.13395599],
       [-0.40051061, -1.23409816, -0.57841395, -0.1431988 , -0.66699252],
       [-0.95310949,  0.94316171,  1.73513473,  0.27081253, -0.58506458],
       [ 0.66168503, -2.09669278,  0.80328168,  2.02779694,  0.57611275]])

In [49]:
# random.randint(low, high=None, size=None, dtype=int)
# generates ONE random integer value between 1 and 100
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

np.random.randint(1,100)

89

In [11]:
# generates 10 random integers values between 1 and 100. The samples
# will be returned in a 10 element array
np.random.randint(1,11,100)

array([ 4,  4,  6, 10,  3,  9,  7,  5,  7,  6,  5,  8,  9,  5,  6,  1, 10,
        7, 10,  7,  1,  1,  9,  7, 10,  8,  9,  5,  3,  5,  9,  9,  9,  2,
        7,  3,  5, 10,  2,  1,  7,  7, 10,  7,  8,  2,  4,  8,  8,  7,  9,
        5,  6,  9,  6,  4,  4,  3,  6,  2,  1, 10,  5,  5,  7,  6,  4,  8,
        8, 10,  5, 10,  2,  6,  7,  2,  6,  9,  5, 10,  7,  4,  7,  3,  3,
        3,  7,  6,  8,  1,  4,  2, 10,  1,  8,  6,  7,  2,  7,  3])

In [23]:
# generates 2*3 random integers values between 1 and 100. The samples
# will be returned in a 2-rows by 3-column matrix
np.random.randint(1, 11, (3,10) ) #  EQUIVALENT --> np.random.randint(1, 100, size=(2,3))

array([[ 3,  4,  6,  2,  3, 10, 10,  3,  7,  9],
       [ 1,  8,  6,  1,  8,  4, 10,  7,  6,  6],
       [ 5,  6,  2,  5,  6, 10,  5,  6,  4,  8]])

In [55]:
# Generates an array of 10 elements - between zero and 2 (2 excluded)
np.random.randint(2, size=10)

array([0, 0, 1, 0, 0, 1, 0, 1, 1, 1])

In [57]:
# Generates an array of 8 elements - between 0 and 4 (4 excluded)
np.random.randint(4, size=8)

array([3, 1, 2, 2, 1, 3, 3, 0])

In [61]:
# Do you need numbers that have reproducibility
# then use a random seed - execute this cell multiple times and observe
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

# RESHAPING

In [63]:
#Step 1: Generate the data
#reshape a one-D vector into a 2-D array (matrix)

ecArray = np.random.randint(0,20,16)
ecArray

array([ 6, 18, 10, 10,  3,  7,  2,  1, 11,  5,  1,  0, 11, 11, 16,  9])

In [65]:
# Step 2. Check the size
#checking the shape of our array
ecArray.shape
print(f"this is known as rank 1 array: {ecArray.shape}")

this is known as rank 1 array: (16,)


In [ ]:
# Step 3. Try to reshape it.
# this one will fail. WHY ?? -->The answer is related to the previous cell
ecArray.reshape(4,5)

In [ ]:
# Step 3. Try to reshape it.
# this one will fail?? why??
ecArray.reshape(4,3)

In [67]:
# Step 3. Try to reshape it.
# this one will work?? why??
ecArray.reshape(4,4)

array([[ 6, 18, 10, 10],
       [ 3,  7,  2,  1],
       [11,  5,  1,  0],
       [11, 11, 16,  9]])

In [69]:
# finds the maximum
print(ecArray)
print(ecArray.max())
print(np.max(ecArray))

[ 6 18 10 10  3  7  2  1 11  5  1  0 11 11 16  9]
18
18


In [71]:
# returns the indices of the maximum values along an axis.
print(ecArray)
print(ecArray.argmax())
print(np.argmax(ecArray))

[ 6 18 10 10  3  7  2  1 11  5  1  0 11 11 16  9]
1
1


In [73]:
# finds the minimum
print(ecArray)
print(ecArray.min())
print(np.min(ecArray))

[ 6 18 10 10  3  7  2  1 11  5  1  0 11 11 16  9]
0
0


In [75]:
#returns the indices of the minimum values along an axis.
print(ecArray)
print(ecArray.argmin())
print(np.argmin(ecArray))

[ 6 18 10 10  3  7  2  1 11  5  1  0 11 11 16  9]
11
11


In [25]:
# Generate 10 integers numbers between 1 and 100
intArray =  np.random.randint(1,100,100)
intArray

array([43, 12, 39, 71, 10, 25, 31, 19, 55, 33, 86, 33,  8, 70, 32, 18, 84,
       29,  2, 59,  7, 33, 96,  3, 87, 80, 31, 74, 70, 95, 17, 71, 55, 77,
       64, 97, 73, 99, 41, 44, 28, 34, 99, 22, 92, 76, 23, 91, 23, 28, 25,
       64,  8,  4, 64,  9, 64, 33, 21, 82,  8, 56, 49, 47, 36, 89, 17, 49,
       12, 93, 22, 65,  9, 18, 24, 54, 35, 73, 93,  2, 75, 70, 62, 40, 69,
       20, 63, 40, 21, 10, 28, 38, 93, 58, 92, 82,  7, 85, 53, 79])

In [79]:
# how to examine what type your array is
intArray.dtype

dtype('int32')

In [81]:
# randombly 
floatArray =  np.random.rand(4)
floatArray

array([0.98323089, 0.46676289, 0.85994041, 0.68030754])

In [83]:
# how to examine what type your array is
print(floatArray.dtype)

float64
