# 1) Numpy Arithmetic Array Fxs
https://numpy.org/doc/stable/reference/routines.math.html

# 2) Numpy Universal Array Fxs
https://numpy.org/doc/stable/reference/ufuncs.html

# 3) Numpy Statistics Fxs
https://numpy.org/doc/stable/reference/routines.statistics.html


# Broadcasting
https://numpy.org/doc/stable/user/basics.broadcasting.html

In [1]:
import numpy as np 

In [2]:
myArray = np.arange(10, -1, -1)
print(myArray)

[10  9  8  7  6  5  4  3  2  1  0]


# Arithmetic between an array and a scalar

In [3]:
# example 1
# it will be an element wise operations (element by element)
print(myArray + 20)

[30 29 28 27 26 25 24 23 22 21 20]


In [4]:
# example 2
# it will be an element wise operations (element by element)
print(myArray - 5)

[ 5  4  3  2  1  0 -1 -2 -3 -4 -5]


# Arithmetic between arrays

In [5]:
# Example 1 - ELEMENT WISE (ELEMENT TO ELEMENT)
# [10  9  8  7  6  5  4  3  2  1  0] 
#                  +
# [10  9  8  7  6  5  4  3  2  1  0]
#                  =
# [20 18 16 14 12 10  8  6  4  2  0]
print(myArray + myArray)

[20 18 16 14 12 10  8  6  4  2  0]


# How Numpy Handles division by zero

In [6]:
# Example 1
# NAN = NOT A NUMBER = 0/0
print(myArray/myArray)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1. nan]


D:\SwInstalledHere\Miniconda3\envs\tensorflow1X\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [7]:
# Example 2 (PYTHON ONLY - THIS CELL DOES NOT HAVE ANY NUMPY)
1/0

ZeroDivisionError: division by zero

In [8]:
# Example 3
# INFINITY  = SCALAR / 0 (NUMPY)
# NUMPY DOES NOT GIVE YOU BACK A FULL ERROR, IT WILL GIVE YOU BACK WARNINGS
# BUT STILL PROCESSES THE INSTRUCTION. THIS DOES NOT CRASH YOUR PROGRAM
print(1/myArray)

[0.1        0.11111111 0.125      0.14285714 0.16666667 0.2
 0.25       0.33333333 0.5        1.                inf]


D:\SwInstalledHere\Miniconda3\envs\tensorflow1X\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


# Some Arithmetic Functions

In [9]:
# let's visualize the source array once again
myArray = np.arange(10, -1, -1)
print(myArray)

[10  9  8  7  6  5  4  3  2  1  0]


In [10]:
# Example 1
# computing the square root of all values in an array
arraySqrt = np.sqrt(myArray)
print(arraySqrt)

[3.16227766 3.         2.82842712 2.64575131 2.44948974 2.23606798
 2.         1.73205081 1.41421356 1.         0.        ]


In [11]:
# Example # 2
# RE-define the array
myArray = np.arange(0,405,45 )
print(myArray)

[  0  45  90 135 180 225 270 315 360]


In [12]:
# Example 2 - CONTINUES
# convert degrees to radians 
myArray = myArray * (np.pi / 180.)
np.sin(myArray)

array([ 0.00000000e+00,  7.07106781e-01,  1.00000000e+00,  7.07106781e-01,
        1.22464680e-16, -7.07106781e-01, -1.00000000e+00, -7.07106781e-01,
       -2.44929360e-16])

In [13]:
# Example 3
# RE-define the array
myArray = np.arange(0,405,45 )
print(myArray)

[  0  45  90 135 180 225 270 315 360]


In [14]:
# Example 3 - CONTINUES
# ALTERNATIVE WAY TO CONVERT FROM DEGREES TO RADIANS
myArray = np.radians(myArray)
np.sin(myArray)

array([ 0.00000000e+00,  7.07106781e-01,  1.00000000e+00,  7.07106781e-01,
        1.22464680e-16, -7.07106781e-01, -1.00000000e+00, -7.07106781e-01,
       -2.44929360e-16])

In [17]:
# Example 4
# RE-define the array
myArray = np.array([0, 1 ,10, 100, 1000, 10000, 100000, 1000000])
print(myArray)

[      0       1      10     100    1000   10000  100000 1000000]


In [18]:
# Example 4 - CONTINUES
myArray = np.log10(myArray)
print(myArray)

[-inf   0.   1.   2.   3.   4.   5.   6.]


D:\SwInstalledHere\Miniconda3\envs\tensorflow1X\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log10
  


# Some Numpy Statistical Fxs

In [19]:
# let's Re-define the array
myArray = np.arange(1, 101, 1)
print(myArray)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [20]:
# example 1
# summation of all elements in an array
sumOfElements = np.sum(myArray)
print(sumOfElements)

5050


In [21]:
# example 2
# compute the mean (mathematical average) of all elements in an array
arrayMean = np.mean(myArray)
print(arrayMean)

50.5


In [22]:
# example 3
# find the maximum and minimum in an array
arrayMax = np.max(myArray)
arrayMin = np.min(myArray)
print("The Maximum is: ", arrayMax)
print("The Minimum is: ", arrayMin)

The Maximum is:  100
The Minimum is:  1


In [23]:
# example 4
# find the variance
arrayVar = np.var(myArray)
print(arrayVar)

833.25


In [24]:
# example 5
# find the standard deviation
arrayStd = np.std(myArray)
print(arrayStd)

28.86607004772212


# Axis Logic in 2D Arrays

In [25]:
# let's redefine the array 
myArray = np.arange(24, -1, -1)
print(myArray)

[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1
  0]


In [26]:
# how many elements do I have in this array?
print("This array has ", np.size(myArray), "Elements")
print("This array dimensions are: ", np.shape(myArray))

This array has  25 Elements
This array dimensions are:  (25,)


In [27]:
# let's RESHAPE this array, into something that has really two dimensions
myMatrix = myArray.reshape(5,5)
print(myMatrix)

# this works because the original array had 25 elements  = rows * columns 
# where chosen wisely

[[24 23 22 21 20]
 [19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


In [28]:
# how many elements do I have in this array?
print("This array has ", np.size(myMatrix), "Elements")
print("This array dimensions are: ", np.shape(myMatrix))
print("This array dimensions are: ", myMatrix.shape)

This array has  25 Elements
This array dimensions are:  (5, 5)
This array dimensions are:  (5, 5)


In [ ]:
# Example 1
# let's find the sum of all elements in this matrix
sumOfElements = np.sum(myMatrix)
print(sumOfElements)

In [29]:
# Example 2
# let's find the sum of all elements in this matrix
sumOfElements = myMatrix.sum()
print(sumOfElements)

300


In [30]:
# Example 3
# let's find the sum of all elements in each single colum in this matrix
print(myMatrix)
sumOfColumns = myMatrix.sum(axis = 0)
print(sumOfColumns)

[[24 23 22 21 20]
 [19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]
[70 65 60 55 50]


In [ ]:
# Example 3
# let's find the sum of all elements in each single row in this matrix
sumOfRows = myMatrix.sum(axis = 1)
print(sumOfRows)