In [2]:
# Import the library
import numpy as np

In [11]:
# define you array, this one has 11 elements
myArray = np.arange(10,-1, -1)
myArray

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# INDEXING

In [16]:
#lets use basic indexing
#examples 1,2,3
print(myArray[0])
print(myArray[2])
print(myArray[4])
print(myArray[10])

10
8
6
0


# SLICING


In [17]:
#let's look at the original array
print(myArray)

[10  9  8  7  6  5  4  3  2  1  0]


In [18]:
# Example 1
# now let's proceed to slice, take a chunck from index 1 to 3 
# Be aware that (index 3 will be EXCLUDED)
slice1 = myArray[1:3]
print(slice1)

[9 8]


In [19]:
#Example 2
slice2 = myArray[0:5]
print(slice2)

[10  9  8  7  6]


In [20]:
#Example 3
slice3 = myArray[1:5]
print(slice3)

[9 8 7 6]


In [21]:
#Example 4
# from index 5 all the way to the last index
# Be aware that the last index element WILL BE INCLUDED
slice4 = myArray[5:]
print(slice4)

[5 4 3 2 1 0]


In [23]:
#Example 5
# from index 0 all the way to index 5
# Be aware that the ELEMENT in index 5 WILL BE EXCLUDED
slice5 = myArray[:5]
print(slice5)

[10  9  8  7  6]


In [24]:
#Example 6
# from index 0 all the way to last index
# if : is the only one included, then it means ALL of them
slice6 = myArray[:]
print(slice6)

[10  9  8  7  6  5  4  3  2  1  0]


# BROADCASTING

In [25]:
#let's look at the original array
print(myArray)

[10  9  8  7  6  5  4  3  2  1  0]


In [26]:
# let's broadcast this number (12345) into the array, specifically
# indexes zero, one, two, three and four
# Be aware that the original arry has changed. That is visualized with 
# the print function
myArray[0:5]=12345
print(myArray)

[12345 12345 12345 12345 12345     5     4     3     2     1     0]


In [29]:
#example 2 - Broadcasting in Matrices
# multiplication example 
myMatrix = np.ones((4,4))
print(myMatrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
# example 2 - continues
# be aware that original matrix value has not changed
print(myMatrix * 5)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [35]:
# example 3 - Matrix + scalar
# be aware that original matrix value has not changed
print(myMatrix  +  5)

[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]


# BROADCASTING - IMPORTANT

In [37]:
# REdefine you array, this one has 11 elements
myArray = np.arange(10,-1, -1)
print(myArray)

[10  9  8  7  6  5  4  3  2  1  0]


In [38]:
# We are about to get a slice of this array
# Be aware that arraySlice is pointing to myArray. You are creating such
# relationship here.
arraySlice = myArray[0:5]
print(arraySlice)

[10  9  8  7  6]


In [39]:
arraySlice[:] = 123   # here we are modifying all of its samples
print(arraySlice)     # printing the whole slice
print(myArray)        # printing the whole source array

# OBSERVE THE CHANGE ON THE SOURCE ARRAY.
# THIS IS DANGEROUS, IT MEANS YOU CAN MODIFY/ALTER/CHANGE THE SOURCE ARRAY

[123 123 123 123 123]
[123 123 123 123 123   5   4   3   2   1   0]


In [5]:
# SO WHAT TO DO???
# create a copy of the original array, like a secondary source
# in other words, you will need to explicitly set a copy.
# this is done in python with the .copy() method

# REdefine you array, this one has 11 elements
myArray = np.arange(10,-1, -1)
#myArrayCopy = myArray
myArrayCopy = myArray.copy()


print(myArray)
print(myArrayCopy)

[10  9  8  7  6  5  4  3  2  1  0]
[10  9  8  7  6  5  4  3  2  1  0]


In [6]:
# so far so good, now let's try again
myArrayCopy[:] = 111
print(myArray)
print(myArrayCopy)

[10  9  8  7  6  5  4  3  2  1  0]
[111 111 111 111 111 111 111 111 111 111 111]


# 2D INDEXING & SLICING 

In [43]:
myMatrix = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(myMatrix)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [44]:
# How to get the dimensions of a matrix?
# ANSWER: with the "shape"  method
# The answer will have this format (rows,columns)
myMatrix.shape

(3, 3)

In [45]:
# how to get a row, for example row zero
print(myMatrix[0])

[9 8 7]


In [46]:
# how to get a row, for example row one
print(myMatrix[1])

[6 5 4]


In [55]:
# how to get the element located at row 2 column 1? --> 2
print(myMatrix[2,1])

2


In [64]:
# how to get the 2x2 bottom-right corner/matrix
myMatrix[1:,1:]

array([[5, 4],
       [2, 1]])

In [62]:
# how to get the 2x2 upper-left corner/matrix
myMatrix[0:2, 0:2]

array([[9, 8],
       [6, 5]])

# CONDITIONAL SELECTION

In [65]:
# REdefine you array, this one has 11 elements
myArray = np.arange(10,-1, -1)
print(myArray)

[10  9  8  7  6  5  4  3  2  1  0]


In [66]:
#STEP 1
#design and & visualize your filter. Are you happy with the results?
myArray > 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [67]:
#STEP 2
#if you are happy with the results, then now you
# can save it and create the filter that you will use

myBooleanArray = (myArray > 5) #filter created here
print(myBooleanArray) #filter being visualized here

[ True  True  True  True  True False False False False False False]


In [69]:
#STEP 3
#use your filter, 
# and get the values that respect/fulfill the filtering criteria
print(myArray[myBooleanArray])

[10  9  8  7  6]


In [70]:
# CAN I DO BETTER? CAN I DO THIS WITH LESS INTRUCTIONS?
# ANSWER" YES
# format:  arrayName(filter here)
print(myArray[myArray > 5])    

[10  9  8  7  6]
