In [1]:
# This is how you import Numpy
import numpy as np  

# * let's define a RANK 1 array. 
* A Rank 1 array is an array with a number of dimensions equal to 1.
* Using this type of array is the most common source of mistakes when dealing with DL algorithms

In [2]:
a2 = np.array([12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
a3 = a2
print("a) prints the original array =" + str(a2))
print("b) Array Dimensions = a1.shape =" + str(a2.shape))
print("b.1) This is how you get the RANK (a2.ndim) = " + str(a2.ndim))
print("b.2) This is a RANK 1 Array = \n" + str(a2))

a) prints the original array =[12 11 10  9  8  7  6  5  4  3  2  1]
b) Array Dimensions = a1.shape =(12,)
b.1) This is how you get the RANK (a2.ndim) = 1
b.2) This is a RANK 1 Array = 
[12 11 10  9  8  7  6  5  4  3  2  1]


# * let's define a RANK 2 array.
* A Rank 2 array is an array with a number of dimensions equal to TWO.
* DO NOT USE RANK 1, USE RANK 2 TO REPRESENT RANK 1

In [3]:
print("---------------------------------------------")
a2 = np.reshape(a2,(2,3,2))
print("c) Array Dimensions (Rows, Cols)= a1.shape =" + str(a2.shape))
print("d) Number of Dimensions = ")
print("e) This is a RANK 3 Array = \n" + str(a2))
print("f) This is how you get the RANK (a2.ndim) = " + str(a2.ndim))
print("g) Number Rows a2.shape[0]=" + str(a2.shape[0]))
print("h) Number Columns a2.shape[1]=" + str(a2.shape[1]))
print("i) Number Columns a2.shape[2]=" + str(a2.shape[2]))
print("j) Number of Elements in array = len(a2) =" + str((a2.shape[0]*a2.shape[1]*a2.shape[2])))  
print("---------------------------------------------")


---------------------------------------------
c) Array Dimensions (Rows, Cols)= a1.shape =(2, 3, 2)
d) Number of Dimensions = 
e) This is a RANK 3 Array = 
[[[12 11]
  [10  9]
  [ 8  7]]

 [[ 6  5]
  [ 4  3]
  [ 2  1]]]
f) This is how you get the RANK (a2.ndim) = 3
g) Number Rows a2.shape[0]=2
h) Number Columns a2.shape[1]=3
i) Number Columns a2.shape[2]=2
j) Number of Elements in array = len(a2) =12
---------------------------------------------


# How to convert Rank 1 to Rank 2 Array

In [4]:
a2 = np.array([12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1])  # Rank 1
a2 = np.reshape(a2,(1,12))

now lets look at this again

In [5]:
print("a) prints the original array =" + str(a2))
print("b) Array Dimensions = a1.shape =" + str(a2.shape))
print("b.1) This is how you get the RANK (a2.ndim) = " + str(a2.ndim))
print("b.2) This is a RANK 2 Array = \n" + str(a2))

a) prints the original array =[[12 11 10  9  8  7  6  5  4  3  2  1]]
b) Array Dimensions = a1.shape =(1, 12)
b.1) This is how you get the RANK (a2.ndim) = 2
b.2) This is a RANK 2 Array = 
[[12 11 10  9  8  7  6  5  4  3  2  1]]
