# This is all based on Numpy which is better than just python

In [2]:
import numpy as np

## Rank 1 Array

In [3]:
a1 = np.array([55, 44, 33, 22, 11])
print("a) Print a1 = " + str(a1))
print("b) Array Dimensions = a1.shape =" + str(a1.shape))
print("c) Number of Elements in array = a1.shape[0] =" + str(a1.shape[0])) 
print("d) Number of Elements in array = len(a1) =" + str(len(a1))) 

a) Print a1 = [55 44 33 22 11]
b) Array Dimensions = a1.shape =(5,)
c) Number of Elements in array = a1.shape[0] =5
d) Number of Elements in array = len(a1) =5


## Creating a Rank 2 Array from a Rank 1 Array

In [4]:
a2 = np.array([12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
a3 = a2
print("a) prints the original array =" + str(a2))
print("b) Array Dimensions = a1.shape =" + str(a2.shape))
print("b.1) This is how you get the RANK (a2.ndim) = " + str(a2.ndim))
print("b.2) This is a RANK 1 Array = \n" + str(a2))
print("---------------------------------------------")
a2 = np.reshape(a2,(4,3))
print("c) Array Dimensions (Rows, Cols)= a1.shape =" + str(a2.shape))
print("d) Number of Dimensions = ")
print("e) This is a RANK 2 Array = \n" + str(a2))
print("f) This is how you get the RANK (a2.ndim) = " + str(a2.ndim))
print("g) Number Rows a2.shape[0]=" + str(a2.shape[0]))
print("h) Number Columns a2.shape[1]=" + str(a2.shape[1]))
print("i) Number of Elements in array = len(a2) =" + str((a2.shape[0]*a2.shape[1])))  
print("---------------------------------------------")
a3 = np.reshape(a3,(1,12))
print("j) prints the original array =" + str(a3))
print("k) Array Dimensions = a3.shape =" + str(a3.shape))

a) prints the original array =[12 11 10  9  8  7  6  5  4  3  2  1]
b) Array Dimensions = a1.shape =(12,)
b.1) This is how you get the RANK (a2.ndim) = 1
b.2) This is a RANK 1 Array = 
[12 11 10  9  8  7  6  5  4  3  2  1]
---------------------------------------------
c) Array Dimensions (Rows, Cols)= a1.shape =(4, 3)
d) Number of Dimensions = 
e) This is a RANK 2 Array = 
[[12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]
f) This is how you get the RANK (a2.ndim) = 2
g) Number Rows a2.shape[0]=4
h) Number Columns a2.shape[1]=3
i) Number of Elements in array = len(a2) =12
---------------------------------------------
j) prints the original array =[[12 11 10  9  8  7  6  5  4  3  2  1]]
k) Array Dimensions = a3.shape =(1, 12)


# Array and Matrix Full of zeros or ones

## Array and Matrix initialized with Zeros

In [4]:
a3 = np.zeros(12)
a4 = np.zeros((4,4))
print("a) a3 =\n " + str(a3))
print("b) a3 rank = " + str(a3.ndim))
print("-------------------------- ")
print("c) a4 =\n " + str(a4))
print("d) a4 rank = " + str(a4.ndim))

a) a3 =
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
b) a3 rank = 1
-------------------------- 
c) a4 =
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
d) a4 rank = 2


## Array and Matrix Initialized with Ones

In [6]:
a5 = np.ones(12)
a6 = np.ones((4,4))
print("a) a5 =\n " + str(a5))
print("b) a5 rank = " + str(a5.ndim))
print("-------------------------- ")
print("c) a6 =\n " + str(a6))
print("d) a6 rank = " + str(a6.ndim))

a) a5 =
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
b) a5 rank = 1
-------------------------- 
c) a6 =
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
d) a6 rank = 2


## Array initialized to some values

In [7]:
a7=np.arange(0,100, 10)  # arange(First, Last, Step or Increase)
print("a7 =", a7)

a7 = [ 0 10 20 30 40 50 60 70 80 90]


In [7]:
a8=np.arange(-2,2, 0.25)  # arange(First, Last, Step or Increase)
print("a8 =", a8)

a8 = [-2.   -1.75 -1.5  -1.25 -1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75
  1.    1.25  1.5   1.75]


## Randomly Initialized Matrix

https://chrisalbon.com/python/basics/generating_random_numbers_with_numpy/

In [8]:
# RANDOM FLOATS [0, 1) = np.random.rand(Rows, Columns) 
a9 = np.random.rand(2, 3)  
print("a9 = \n" + str(a9))

a9 = 
[[0.97231366 0.50120511 0.01840847]
 [0.72625157 0.05458631 0.22303107]]


In [9]:
# RANDOM INTEGERS = np.random.randint(Low, High, size=(Rows,Cols)) 
a10 = np.random.randint(2, 10, size=(2,3))
print("a10 = \n" + str(a10))

a10 = 
[[6 6 6]
 [3 5 9]]


In [10]:
a11 = np.random.randint(2, 10, size=(2,3))

# Broadcasting Examples

In [11]:
# BROADCASTING ADDITION
print("a) Before Adding 22 to a5 = ", str(a5))
print("b) After  Adding 22 to a5 = ", str(a5 + 22))

a) Before Adding 22 to a5 =  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
b) After  Adding 22 to a5 =  [23. 23. 23. 23. 23. 23. 23. 23. 23. 23. 23. 23.]


In [12]:
# BROADCASTING MULTIPLICATION
print("a) Before *ing each element of a5 by 5 = ", str(a5))
print("b) After  *ing each element of a5 by 5 = ", str(a5 * 5))

a) Before *ing each element of a5 by 5 =  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
b) After  *ing each element of a5 by 5 =  [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# Matrix Addition, Element Wise Mult. and Algebraic Matrix Multiplication

# # Matrix Addition

In [13]:
m1 = np.array([[1, 2], [3, 4]])
m2 = m1;
mx = np.array([[1, 2], [3, 4], [5, 6]])

print("a) m1 = m2 = \n", str(m1))
print("==============================")
mAddition1 = m1 + m2 
print("b) m1 + m2 = \n", str(m1 + m2))
print("==============================")

a) m1 = m2 = 
 [[1 2]
 [3 4]]
b) m1 + m2 = 
 [[2 4]
 [6 8]]


# # Element Wise Matrix Multiplication (2 Methods)

In [14]:
# This will do ELEMENT-WISE multiplication, NOT REAL MATRIX MULT.
print("Method 1: THIS IS ELEMENT-WISE MULT. Not real Matrix Mult.")
mMultiplication1 = m1 * m2  
print("a) m1 * m2 = \n", str(mMultiplication1))
print("==============================")

print("Method 2: THIS IS ELEMENT-WISE MULT. Not real Matrix Mult.")
# This will do ELEMENT-WISE multiplication, NOT REAL MATRIX MULT.
mMultiplication2 = np.multiply(m1, m2) 
print("b) np.multiply(m1, m2) = \n", str(mMultiplication2))
print("==============================")

Method 1: THIS IS ELEMENT-WISE MULT. Not real Matrix Mult.
a) m1 * m2 = 
 [[ 1  4]
 [ 9 16]]
Method 2: THIS IS ELEMENT-WISE MULT. Not real Matrix Mult.
b) np.multiply(m1, m2) = 
 [[ 1  4]
 [ 9 16]]


# # Algebraic Matrix Multiplication

In [15]:
print("THIS IS REAL MATRIX MULT. This is NOT Element Wise Mult.")
# THIS IS THE REAL ALGEBRAIC MATRIX MULT. THIS IS NOT ELEMENT WISE Mult
mMultiplication3 = np.dot(m1, m2)  

print("a) np.dot(m1, m2) = \n", str(mMultiplication3))
print("==============================")

THIS IS REAL MATRIX MULT. This is NOT Element Wise Mult.
a) np.dot(m1, m2) = 
 [[ 7 10]
 [15 22]]
